
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYassign(node * arg_node, info * arg_info) {
	node           *result = TBmakeAssign(NULL, NULL);
	DBUG_ENTER("COPYassign");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	ASSIGN_LET(result) = COPYTRAV(ASSIGN_LET(arg_node), arg_info);
	ASSIGN_EXPR(result) = COPYTRAV(ASSIGN_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYbinop(node * arg_node, info * arg_info) {
	node           *result = TBmakeBinop(BO_unknown, NULL, NULL);
	DBUG_ENTER("COPYbinop");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	BINOP_OP(result) = BINOP_OP(arg_node);
	/* Copy sons */
	BINOP_LEFT(result) = COPYTRAV(BINOP_LEFT(arg_node), arg_info);
	BINOP_RIGHT(result) = COPYTRAV(BINOP_RIGHT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYbool(node * arg_node, info * arg_info) {
	node           *result = TBmakeBool(FALSE);
	DBUG_ENTER("COPYbool");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	BOOL_VALUE(result) = BOOL_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYdecls
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Decls node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYdecls(node * arg_node, info * arg_info) {
	node           *result = TBmakeDecls(NULL, NULL);
	DBUG_ENTER("COPYdecls");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	DECLS_DECL(result) = COPYTRAV(DECLS_DECL(arg_node), arg_info);
	DECLS_NEXT(result) = COPYTRAV(DECLS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYdowhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYdowhile(node * arg_node, info * arg_info) {
	node           *result = TBmakeDowhile(NULL, NULL);
	DBUG_ENTER("COPYdowhile");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	DOWHILE_COND(result) = COPYTRAV(DOWHILE_COND(arg_node), arg_info);
	DOWHILE_BLOCK(result) = COPYTRAV(DOWHILE_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYerror(node * arg_node, info * arg_info) {
	node           *result = TBmakeError(NULL, PH_initial, NULL);
	DBUG_ENTER("COPYerror");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	ERROR_MESSAGE(result) = STRcpy(ERROR_MESSAGE(arg_node));
	ERROR_ANYPHASE(result) = ERROR_ANYPHASE(arg_node);
	/* Copy sons */
	ERROR_NEXT(result) = COPYTRAV(ERROR_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfloat(node * arg_node, info * arg_info) {
	node           *result = TBmakeFloat(0.0);
	DBUG_ENTER("COPYfloat");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FLOAT_VALUE(result) = FLOAT_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfor(node * arg_node, info * arg_info) {
	node           *result = TBmakeFor(NULL, NULL, NULL, NULL, NULL);
	DBUG_ENTER("COPYfor");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FOR_LOOPVAR(result) = STRcpy(FOR_LOOPVAR(arg_node));
	/* Copy sons */
	FOR_START(result) = COPYTRAV(FOR_START(arg_node), arg_info);
	FOR_STOP(result) = COPYTRAV(FOR_STOP(arg_node), arg_info);
	FOR_STEP(result) = COPYTRAV(FOR_STEP(arg_node), arg_info);
	FOR_BLOCK(result) = COPYTRAV(FOR_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfunbody(node * arg_node, info * arg_info) {
	node           *result = TBmakeFunbody(NULL, NULL, NULL);
	DBUG_ENTER("COPYfunbody");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	FUNBODY_VARDECLS(result) = COPYTRAV(FUNBODY_VARDECLS(arg_node), arg_info);
	FUNBODY_LOCALFUNDEFS(result) = COPYTRAV(FUNBODY_LOCALFUNDEFS(arg_node), arg_info);
	FUNBODY_STMTS(result) = COPYTRAV(FUNBODY_STMTS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundec(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundec(NULL);
	DBUG_ENTER("COPYfundec");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy flags */
	FUNDEC_ISEXTERN(result) = FUNDEC_ISEXTERN(arg_node);
	/* Copy sons */
	FUNDEC_FUNHEADER(result) = COPYTRAV(FUNDEC_FUNHEADER(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundef(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundef(NULL, NULL);
	DBUG_ENTER("COPYfundef");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy flags */
	FUNDEF_ISEXPORT(result) = FUNDEF_ISEXPORT(arg_node);
	/* Copy sons */
	FUNDEF_FUNHEADER(result) = COPYTRAV(FUNDEF_FUNHEADER(arg_node), arg_info);
	FUNDEF_FUNBODY(result) = COPYTRAV(FUNDEF_FUNBODY(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundefs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDefs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundefs(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundefs(NULL, NULL);
	DBUG_ENTER("COPYfundefs");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	FUNDEFS_FUNDEF(result) = COPYTRAV(FUNDEFS_FUNDEF(arg_node), arg_info);
	FUNDEFS_NEXT(result) = COPYTRAV(FUNDEFS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfunheader(node * arg_node, info * arg_info) {
	node           *result = TBmakeFunheader(NULL);
	DBUG_ENTER("COPYfunheader");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FUNHEADER_TYPE(result) = FUNHEADER_TYPE(arg_node);
	FUNHEADER_NAME(result) = STRcpy(FUNHEADER_NAME(arg_node));
	/* Copy sons */
	FUNHEADER_PARAMS(result) = COPYTRAV(FUNHEADER_PARAMS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYglobdec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYglobdec(node * arg_node, info * arg_info) {
	node           *result = TBmakeGlobdec(NULL, TY_unknown);
	DBUG_ENTER("COPYglobdec");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	GLOBDEC_NAME(result) = STRcpy(GLOBDEC_NAME(arg_node));
	GLOBDEC_TYPE(result) = GLOBDEC_TYPE(arg_node);
	/* Copy flags */
	GLOBDEC_ISEXTERN(result) = GLOBDEC_ISEXTERN(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYglobdef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYglobdef(node * arg_node, info * arg_info) {
	node           *result = TBmakeGlobdef(NULL, TY_unknown, NULL);
	DBUG_ENTER("COPYglobdef");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	GLOBDEF_NAME(result) = STRcpy(GLOBDEF_NAME(arg_node));
	GLOBDEF_TYPE(result) = GLOBDEF_TYPE(arg_node);
	/* Copy flags */
	GLOBDEF_ISEXPORT(result) = GLOBDEF_ISEXPORT(arg_node);
	/* Copy sons */
	GLOBDEF_EXPR(result) = COPYTRAV(GLOBDEF_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYifelse
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IfElse node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYifelse(node * arg_node, info * arg_info) {
	node           *result = TBmakeIfelse(NULL, NULL, NULL);
	DBUG_ENTER("COPYifelse");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	IFELSE_COND(result) = COPYTRAV(IFELSE_COND(arg_node), arg_info);
	IFELSE_THEN(result) = COPYTRAV(IFELSE_THEN(arg_node), arg_info);
	IFELSE_ELSE(result) = COPYTRAV(IFELSE_ELSE(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYmonop(node * arg_node, info * arg_info) {
	node           *result = TBmakeMonop(MO_unknown, NULL);
	DBUG_ENTER("COPYmonop");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	MONOP_OP(result) = MONOP_OP(arg_node);
	/* Copy sons */
	MONOP_OPERAND(result) = COPYTRAV(MONOP_OPERAND(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYnum(node * arg_node, info * arg_info) {
	node           *result = TBmakeNum(0);
	DBUG_ENTER("COPYnum");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	NUM_VALUE(result) = NUM_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYparam(node * arg_node, info * arg_info) {
	node           *result = TBmakeParam(TY_unknown);
	DBUG_ENTER("COPYparam");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	PARAM_TYPE(result) = PARAM_TYPE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYparams
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Params node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYparams(node * arg_node, info * arg_info) {
	node           *result = TBmakeParams(NULL, TY_unknown, NULL, NULL);
	DBUG_ENTER("COPYparams");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	PARAMS_NAME(result) = STRcpy(PARAMS_NAME(arg_node));
	PARAMS_TYPE(result) = PARAMS_TYPE(arg_node);
	/* Copy sons */
	PARAMS_PARAM(result) = COPYTRAV(PARAMS_PARAM(arg_node), arg_info);
	PARAMS_NEXT(result) = COPYTRAV(PARAMS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYprogram
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYprogram(node * arg_node, info * arg_info) {
	node           *result = TBmakeProgram(NULL);
	DBUG_ENTER("COPYprogram");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	PROGRAM_DECLS(result) = COPYTRAV(PROGRAM_DECLS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYreturn(node * arg_node, info * arg_info) {
	node           *result = TBmakeReturn(NULL);
	DBUG_ENTER("COPYreturn");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	RETURN_EXPR(result) = COPYTRAV(RETURN_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYstmts
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYstmts(node * arg_node, info * arg_info) {
	node           *result = TBmakeStmts(NULL, NULL);
	DBUG_ENTER("COPYstmts");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	STMTS_STMT(result) = COPYTRAV(STMTS_STMT(arg_node), arg_info);
	STMTS_NEXT(result) = COPYTRAV(STMTS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYsymboltableentry
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYsymboltableentry(node * arg_node, info * arg_info) {
	node           *result = TBmakeSymboltableentry();
	DBUG_ENTER("COPYsymboltableentry");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvar
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvar(node * arg_node, info * arg_info) {
	node           *result = TBmakeVar(NULL);
	DBUG_ENTER("COPYvar");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VAR_NAME(result) = STRcpy(VAR_NAME(arg_node));
	VAR_DECL(result) = LUTsearchInLutPp(INFO_LUT(arg_info), VAR_DECL(arg_node));
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvardecl
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDecl node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvardecl(node * arg_node, info * arg_info) {
	node           *result = TBmakeVardecl(NULL, TY_unknown);
	DBUG_ENTER("COPYvardecl");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VARDECL_NAME(result) = STRcpy(VARDECL_NAME(arg_node));
	VARDECL_TYPE(result) = VARDECL_TYPE(arg_node);
	/* Copy flags */
	VARDECL_ISEXPORT(result) = VARDECL_ISEXPORT(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvardecls
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDecls node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvardecls(node * arg_node, info * arg_info) {
	node           *result = TBmakeVardecls(NULL, NULL);
	DBUG_ENTER("COPYvardecls");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	VARDECLS_VARDECL(result) = COPYTRAV(VARDECLS_VARDECL(arg_node), arg_info);
	VARDECLS_NEXT(result) = COPYTRAV(VARDECLS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvarlet
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvarlet(node * arg_node, info * arg_info) {
	node           *result = TBmakeVarlet(NULL);
	DBUG_ENTER("COPYvarlet");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VARLET_NAME(result) = STRcpy(VARLET_NAME(arg_node));
	VARLET_DECL(result) = LUTsearchInLutPp(INFO_LUT(arg_info), VARLET_DECL(arg_node));
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYwhile(node * arg_node, info * arg_info) {
	node           *result = TBmakeWhile(NULL, NULL);
	DBUG_ENTER("COPYwhile");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	WHILE_COND(result) = COPYTRAV(WHILE_COND(arg_node), arg_info);
	WHILE_BLOCK(result) = COPYTRAV(WHILE_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/**
 * @}
 */
