
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYassign(node * arg_node, info * arg_info) {
	node           *result = TBmakeAssign(NULL, NULL);
	DBUG_ENTER("COPYassign");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	ASSIGN_LET(result) = COPYTRAV(ASSIGN_LET(arg_node), arg_info);
	ASSIGN_EXPR(result) = COPYTRAV(ASSIGN_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYbinop(node * arg_node, info * arg_info) {
	node           *result = TBmakeBinop(BO_unknown, NULL, NULL);
	DBUG_ENTER("COPYbinop");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	BINOP_OP(result) = BINOP_OP(arg_node);
	/* Copy sons */
	BINOP_LEFT(result) = COPYTRAV(BINOP_LEFT(arg_node), arg_info);
	BINOP_RIGHT(result) = COPYTRAV(BINOP_RIGHT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYbool(node * arg_node, info * arg_info) {
	node           *result = TBmakeBool(FALSE);
	DBUG_ENTER("COPYbool");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	BOOL_VALUE(result) = BOOL_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYdeclarations
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYdeclarations(node * arg_node, info * arg_info) {
	node           *result = TBmakeDeclarations(NULL, NULL);
	DBUG_ENTER("COPYdeclarations");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	DECLARATIONS_DECLARATION(result) = COPYTRAV(DECLARATIONS_DECLARATION(arg_node), arg_info);
	DECLARATIONS_NEXT(result) = COPYTRAV(DECLARATIONS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYdowhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYdowhile(node * arg_node, info * arg_info) {
	node           *result = TBmakeDowhile(NULL, NULL);
	DBUG_ENTER("COPYdowhile");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	DOWHILE_CONDITION(result) = COPYTRAV(DOWHILE_CONDITION(arg_node), arg_info);
	DOWHILE_BLOCK(result) = COPYTRAV(DOWHILE_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYerror(node * arg_node, info * arg_info) {
	node           *result = TBmakeError(NULL, PH_initial, NULL);
	DBUG_ENTER("COPYerror");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	ERROR_MESSAGE(result) = STRcpy(ERROR_MESSAGE(arg_node));
	ERROR_ANYPHASE(result) = ERROR_ANYPHASE(arg_node);
	/* Copy sons */
	ERROR_NEXT(result) = COPYTRAV(ERROR_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYexpressions
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Expressions node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYexpressions(node * arg_node, info * arg_info) {
	node           *result = TBmakeExpressions(NULL, NULL);
	DBUG_ENTER("COPYexpressions");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	EXPRESSIONS_EXPR(result) = COPYTRAV(EXPRESSIONS_EXPR(arg_node), arg_info);
	EXPRESSIONS_NEXT(result) = COPYTRAV(EXPRESSIONS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfloat(node * arg_node, info * arg_info) {
	node           *result = TBmakeFloat(0.0);
	DBUG_ENTER("COPYfloat");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FLOAT_VALUE(result) = FLOAT_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfor(node * arg_node, info * arg_info) {
	node           *result = TBmakeFor(NULL, NULL, NULL, NULL);
	DBUG_ENTER("COPYfor");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	FOR_FIRST(result) = COPYTRAV(FOR_FIRST(arg_node), arg_info);
	FOR_SECOND(result) = COPYTRAV(FOR_SECOND(arg_node), arg_info);
	FOR_THIRD(result) = COPYTRAV(FOR_THIRD(arg_node), arg_info);
	FOR_BLOCK(result) = COPYTRAV(FOR_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfunbody(node * arg_node, info * arg_info) {
	node           *result = TBmakeFunbody(NULL, NULL, NULL);
	DBUG_ENTER("COPYfunbody");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	FUNBODY_VARDEC(result) = COPYTRAV(FUNBODY_VARDEC(arg_node), arg_info);
	FUNBODY_LOCALFUNDEFS(result) = COPYTRAV(FUNBODY_LOCALFUNDEFS(arg_node), arg_info);
	FUNBODY_STMTS(result) = COPYTRAV(FUNBODY_STMTS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundec(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundec(TY_unknown, NULL);
	DBUG_ENTER("COPYfundec");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FUNDEC_TYPE(result) = FUNDEC_TYPE(arg_node);
	/* Copy sons */
	FUNDEC_FUNHEADER(result) = COPYTRAV(FUNDEC_FUNHEADER(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundef(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundef(TY_unknown, NULL, NULL);
	DBUG_ENTER("COPYfundef");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FUNDEF_TYPE(result) = FUNDEF_TYPE(arg_node);
	/* Copy flags */
	FUNDEF_ISEXTERN(result) = FUNDEF_ISEXTERN(arg_node);
	FUNDEF_ISEXPORT(result) = FUNDEF_ISEXPORT(arg_node);
	/* Copy sons */
	FUNDEF_FUNBODY(result) = COPYTRAV(FUNDEF_FUNBODY(arg_node), arg_info);
	FUNDEF_PARAMS(result) = COPYTRAV(FUNDEF_PARAMS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfundefs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDefs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfundefs(node * arg_node, info * arg_info) {
	node           *result = TBmakeFundefs(NULL, NULL);
	DBUG_ENTER("COPYfundefs");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	FUNDEFS_FUNDEF(result) = COPYTRAV(FUNDEFS_FUNDEF(arg_node), arg_info);
	FUNDEFS_NEXT(result) = COPYTRAV(FUNDEFS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYfunheader(node * arg_node, info * arg_info) {
	node           *result = TBmakeFunheader(TY_unknown, NULL);
	DBUG_ENTER("COPYfunheader");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	FUNHEADER_TYPE(result) = FUNHEADER_TYPE(arg_node);
	/* Copy sons */
	FUNHEADER_PARAM(result) = COPYTRAV(FUNHEADER_PARAM(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYglobaldec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYglobaldec(node * arg_node, info * arg_info) {
	node           *result = TBmakeGlobaldec(TY_unknown, NULL);
	DBUG_ENTER("COPYglobaldec");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	GLOBALDEC_TYPE(result) = GLOBALDEC_TYPE(arg_node);
	/* Copy sons */
	GLOBALDEC_IDS(result) = COPYTRAV(GLOBALDEC_IDS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYglobaldef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYglobaldef(node * arg_node, info * arg_info) {
	node           *result = TBmakeGlobaldef(TY_unknown, NULL);
	DBUG_ENTER("COPYglobaldef");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	GLOBALDEF_TYPE(result) = GLOBALDEF_TYPE(arg_node);
	/* Copy flags */
	GLOBALDEF_ISEXPORT(result) = GLOBALDEF_ISEXPORT(arg_node);
	/* Copy sons */
	GLOBALDEF_IDS(result) = COPYTRAV(GLOBALDEF_IDS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYids
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Ids node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYids(node * arg_node, info * arg_info) {
	node           *result = TBmakeIds(NULL);
	DBUG_ENTER("COPYids");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	IDS_EXPR(result) = COPYTRAV(IDS_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYifelse
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IfElse node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYifelse(node * arg_node, info * arg_info) {
	node           *result = TBmakeIfelse(NULL, NULL, NULL);
	DBUG_ENTER("COPYifelse");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	IFELSE_CONDITION(result) = COPYTRAV(IFELSE_CONDITION(arg_node), arg_info);
	IFELSE_THEN(result) = COPYTRAV(IFELSE_THEN(arg_node), arg_info);
	IFELSE_ELSE(result) = COPYTRAV(IFELSE_ELSE(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYmonop(node * arg_node, info * arg_info) {
	node           *result = TBmakeMonop(MO_unknown, NULL);
	DBUG_ENTER("COPYmonop");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	MONOP_OP(result) = MONOP_OP(arg_node);
	/* Copy sons */
	MONOP_OPERAND(result) = COPYTRAV(MONOP_OPERAND(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYnum(node * arg_node, info * arg_info) {
	node           *result = TBmakeNum(0);
	DBUG_ENTER("COPYnum");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	NUM_VALUE(result) = NUM_VALUE(arg_node);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYparam(node * arg_node, info * arg_info) {
	node           *result = TBmakeParam(TY_unknown, NULL, NULL);
	DBUG_ENTER("COPYparam");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	PARAM_TYPE(result) = PARAM_TYPE(arg_node);
	/* Copy sons */
	PARAM_ID(result) = COPYTRAV(PARAM_ID(arg_node), arg_info);
	PARAM_NEXT(result) = COPYTRAV(PARAM_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYprogram
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYprogram(node * arg_node, info * arg_info) {
	node           *result = TBmakeProgram(NULL);
	DBUG_ENTER("COPYprogram");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	PROGRAM_DECLARATIONS(result) = COPYTRAV(PROGRAM_DECLARATIONS(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYreturn(node * arg_node, info * arg_info) {
	node           *result = TBmakeReturn(NULL);
	DBUG_ENTER("COPYreturn");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	RETURN_EXPR(result) = COPYTRAV(RETURN_EXPR(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYstmts
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYstmts(node * arg_node, info * arg_info) {
	node           *result = TBmakeStmts(NULL, NULL);
	DBUG_ENTER("COPYstmts");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	STMTS_STMT(result) = COPYTRAV(STMTS_STMT(arg_node), arg_info);
	STMTS_NEXT(result) = COPYTRAV(STMTS_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYsymboltableentry
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYsymboltableentry(node * arg_node, info * arg_info) {
	node           *result = TBmakeSymboltableentry();
	DBUG_ENTER("COPYsymboltableentry");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvar
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvar(node * arg_node, info * arg_info) {
	node           *result = TBmakeVar(NULL);
	DBUG_ENTER("COPYvar");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VAR_NAME(result) = STRcpy(VAR_NAME(arg_node));
	VAR_DECL(result) = LUTsearchInLutPp(INFO_LUT(arg_info), VAR_DECL(arg_node));
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvardec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvardec(node * arg_node, info * arg_info) {
	node           *result = TBmakeVardec(TY_unknown, NULL, NULL);
	DBUG_ENTER("COPYvardec");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VARDEC_TYPE(result) = VARDEC_TYPE(arg_node);
	/* Copy sons */
	VARDEC_EXPRESSIONS(result) = COPYTRAV(VARDEC_EXPRESSIONS(arg_node), arg_info);
	VARDEC_NEXT(result) = COPYTRAV(VARDEC_NEXT(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYvarlet
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYvarlet(node * arg_node, info * arg_info) {
	node           *result = TBmakeVarlet(NULL);
	DBUG_ENTER("COPYvarlet");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy attributes */
	VARLET_NAME(result) = STRcpy(VARLET_NAME(arg_node));
	VARLET_DECL(result) = LUTsearchInLutPp(INFO_LUT(arg_info), VARLET_DECL(arg_node));
	/* Return value */
	DBUG_RETURN(result);
}
/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node           *COPYwhile(node * arg_node, info * arg_info) {
	node           *result = TBmakeWhile(NULL, NULL);
	DBUG_ENTER("COPYwhile");
	LUTinsertIntoLutP(INFO_LUT(arg_info), arg_node, result);
	/* Copy sons */
	WHILE_CONDITION(result) = COPYTRAV(WHILE_CONDITION(arg_node), arg_info);
	WHILE_BLOCK(result) = COPYTRAV(WHILE_BLOCK(arg_node), arg_info);
	/* Return value */
	DBUG_RETURN(result);
}
/**
 * @}
 */
