
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 29
typedef enum {
N_undefined = 0, N_program = 1, N_declarations = 2, N_fundec = 3, N_fundefs = 4, N_fundef = 5, N_funheader = 6, N_globaldec = 7, N_globaldef = 8, N_param = 9, N_funbody = 10, N_vardec = 11, N_ifelse = 12, N_while = 13, N_dowhile = 14, N_for = 15, N_return = 16, N_expressions = 17, N_ids = 18, N_stmts = 19, N_assign = 20, N_binop = 21, N_monop = 22, N_varlet = 23, N_var = 24, N_num = 25, N_float = 26, N_bool = 27, N_symboltableentry = 28, N_error = 29} nodetype;

#endif				/* _SAC_TYPES_NODETYPE_H_ */
