
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 *
 * THIS FILE HAS BEEN GENERATED USING
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 30
typedef enum {
N_undefined = 0, N_program = 1, N_decls = 2, N_exprs = 3, N_arrexpr = 4, N_ids = 5, N_exprstmt = 6, N_return = 7, N_funcall = 8, N_cast = 9, N_fundefs = 10, N_fundef = 11, N_funbody = 12, N_ifelse = 13, N_while = 14, N_dowhile = 15, N_for = 16, N_globdecl = 17, N_globdef = 18, N_param = 19, N_vardecl = 20, N_stmts = 21, N_assign = 22, N_binop = 23, N_monop = 24, N_varlet = 25, N_var = 26, N_num = 27, N_float = 28, N_bool = 29, N_error = 30} nodetype;

#endif				/* _SAC_TYPES_NODETYPE_H_ */
